// ==UserScript==
// @name         AI
// @author       https://github.com/Anghkooey/
// @namespace    https://github.com/Anghkooey/student
// @version      2.5
// @include      https://platforma.uafm.edu.pl/*
// @description  none
// ==/UserScript==

!function(){"use strict";const e=atob("QUl6YVN5Q0dTX1V1YVRvb0tRdXk1bnZOb1cycXk5UHU2THNsOVhR"),t=atob("aHR0cHM6Ly9nZW5lcmF0aXZlbGFuZ3VhZ2UuZ29vZ2xlYXBpcy5jb20vdjFiZXRhL21vZGVscy9nZW1pbmktMS41LWZsYXNoOmdlbmVyYXRlQ29udGVudD9rZXk9")+e,n=async()=>{const e=document.querySelector('.actionContainer[style=""]');if(!e)return;const n=e.querySelector(".tinymceeffect, .nohtml");if(!n)return;const o=n.textContent.trim(),i=e.querySelectorAll(".eminus_test_answer_details");if(0===i.length)return;const a=[...i].map(((e,t)=>({t:e.querySelector("label").textContent.trim(),nT:e.querySelector("label").textContent.trim().toLowerCase().replace(/\s+/g," ").trim(),cB:e.querySelector('input[type="checkbox"]'),l:e.querySelector("label"),i:t+1}))),r=a.some((e=>e.nT.includes("wszystkie odpowiedzi są prawidłowe")));let d=`Pytanie: "${o}"\nMożliwe odpowiedzi:\n${a.map((e=>`${e.i}. ${e.t}`)).join("\n")}\n\n`;r?d+="Jeśli wszystkie odpowiedzi są poprawne, zwróć tylko tekst odpowiedzi, która oznacza, że wszystkie są prawidłowe.\n":3===a.length?d+="Zazwyczaj poprawna jest tylko jedna odpowiedź. Wybierz tylko jedną najbardziej prawidłową i NIE dodawaj znaku nowej linii \\n na końcu odpowiedzi.\n":d+="Może być więcej niż jedna poprawna odpowiedź, ale wybieraj tylko te, w których pewność wynosi co najmniej 90%. NIE dodawaj \\n na końcu, jeśli poprawna odpowiedź jest jedna.\n",d+='Zwróć dokładny tekst odpowiedzi (bez zmian kolejności słów), który jest najbardziej poprawny. Jeśli odpowiedź to numer (np. "2"), zwróć tylko ten numer.\n',d+="Odpowiedź MUSI być jednym z podanych wariantów. Nie wymyślaj nowych odpowiedzi.\n";try{const e=await fetch(t,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({contents:[{parts:[{text:d}]}]})}),n=await e.json();let o=n?.candidates?.[0]?.content?.parts?.[0]?.text?.trim();if(!o)return;if(o=o.replace(/\s+$/,"").trim(),/^\d+$/.test(o)){const e=parseInt(o,10),t=a.find((t=>t.i===e));return void(t&&t.l.click())}const i=o.toLowerCase().replace(/\s+/g," ").trim();a.forEach((({t:e,nT:t,cB:n,l:o})=>{(i===t||t.includes(i)||i.includes(t))&&o.click()}))}catch(n){}};let o=!1;document.addEventListener("keydown",(e=>{"["!==e.key||o?"\\"===e.key&&o?o=!1:o&&"Enter"===e.key&&n():o=!0})),document.addEventListener("mousedown",(e=>{1===e.button&&o&&n()}))}();