// ==UserScript==
// @name         Parser
// @author       https://github.com/Anghkooey/
// @namespace    https://github.com/Anghkooey/student
// @version      1.0
// @include      https://platforma.uafm.edu.pl/*
// @description  none
// @grant        GM_setClipboard
// ==/UserScript==

!function(){"use strict";let e={},t=[];function n(){let n=[],o=1;t=[],document.querySelectorAll(".eminus_test_question").forEach((e=>{let i=e.querySelector(".tinymceeffect, .nohtml")?.textContent.trim(),l=[],r=1,a={};e.querySelectorAll(".eminus_test_answer_details").forEach((e=>{let t=e.querySelector("label")?.textContent.trim();l.push(`${r}. ${t}`),a[r]={element:e,text:t.toLowerCase().replace(/\s+/g," ").trim(),label:e.querySelector("label"),checkbox:e.querySelector("input[type='checkbox']")},r++})),i&&l.length>0&&(n.push(`Pytanie ${o}:\n${i}\n${l.join("\n")}`),t.push({num:o,answers:a,text:i.toLowerCase().trim()}),o++)}));let i=`Jesteś ekspertem w Polsce, znasz wszystkie nowelizacje prawa, nauki oraz inne zmiany.\nTwoim zadaniem jest podanie numeru pytania oraz poprawnych odpowiedzi na podstawie podanych opcji.\n\nPodaj tylko numer pytania i numery poprawnych odpowiedzi, bez dodatkowych wyjaśnień.\n\nJeśli uważasz, że poprawnych odpowiedzi jest więcej niż jedna, dodaj je **tylko jeśli jesteś pewien na 95%**, że są właściwe.\n\nPrzykład odpowiedzi:\n1: 2\n2: 1, 3\n\nPytania i odpowiedzi:\n${n.join("\n\n")}`;GM_setClipboard(i),window.open("https://chat.openai.com/","_blank"),function(){let t=document.createElement("textarea");t.id="gptAnswerBox",t.placeholder="Wklej tutaj odpowiedzi z ChatGPT...",t.style.position="fixed",t.style.top="10px",t.style.right="10px",t.style.width="300px",t.style.height="200px",t.style.zIndex="10000",t.style.padding="10px",t.style.fontSize="14px",t.style.border="2px solid black",t.style.background="white",t.style.color="black";let n=document.createElement("button");n.innerText="Zapisz",n.style.position="fixed",n.style.top="220px",n.style.right="10px",n.style.zIndex="10000",n.onclick=function(){let o=document.getElementById("gptAnswerBox").value.trim();e=function(e){let t={};return e.split("\n").forEach((e=>{let n=e.split(":");if(2===n.length){let e=n[0].trim(),o=n[1].trim().split(",").map((e=>e.trim()));t[e]=o}})),t}(o),document.body.removeChild(t),document.body.removeChild(n)},document.body.appendChild(t),document.body.appendChild(n)}()}document.addEventListener("keydown",(function(o){"]"===o.key?n():"\\"===o.key&&async function(){const n=document.querySelector('.actionContainer[style=""]');if(!n)return;const o=n.querySelector(".tinymceeffect, .nohtml");if(!o)return;const i=o.textContent.trim().toLowerCase();let l=t.find((e=>e.text===i));if(!l)return;let r=l.num,a=e[r];if(!a)return;let c=l.answers;a.forEach((e=>{c[e]&&c[e].label.click()}))}()}))}();
