// ==UserScript==
// @name         Parser
// @author       https://github.com/Anghkooey/
// @namespace    https://github.com/Anghkooey/student
// @version      1.0
// @include      https://platforma.uafm.edu.pl/*
// @description  none
// @grant        GM_setClipboard
// ==/UserScript==

!function(){"use strict";let e={},t=[],n="",o=!1;function i(){let i=[],r=1;t=[],document.querySelectorAll(".eminus_test_question").forEach((e=>{let n=e.querySelector(".tinymceeffect, .nohtml")?.textContent.trim(),o=[],l=1,a={};e.querySelectorAll(".eminus_test_answer_details").forEach((e=>{let t=e.querySelector("label")?.textContent.trim();o.push(`${l}. ${t}`),a[l]={a:e,b:t.toLowerCase().replace(/\s+/g," ").trim(),c:e.querySelector("label"),d:e.querySelector("input[type='checkbox']")},l++})),n&&o.length>0&&(i.push(`Pytanie ${r}:\n${n}\n${o.join("\n")}`),t.push({num:r,answers:a,text:n.toLowerCase().trim()}),r++)})),n=`Jesteś ekspertem w Polsce, znasz wszystkie nowelizacje prawa, nauki oraz inne zmiany.\nTwoim zadaniem jest podanie numeru pytania oraz poprawnych odpowiedzi na podstawie podanych opcji.\n\nPodaj tylko numer pytania i numery poprawnych odpowiedzi, bez dodatkowych wyjaśnień.\n\nJeśli uważasz, że poprawnych odpowiedzi jest więcej niż jedna, dodaj je **tylko jeśli jesteś pewien на 95%**, że są one poprawne.\n\nPrzykładowa odpowiedź:\n1: 2\n2: 1, 3\nPytania i odpowiedzi:\n${i.join("\n\n")}`,GM_setClipboard(n),window.open("https://chat.openai.com/","_blank"),function(){let t=document.createElement("textarea");t.id="gptAnswerBox",t.placeholder="Wklej tutaj odpowiedzi z ChatGPT...",t.style.position="fixed",t.style.top="10px",t.style.right="10px",t.style.width="300px",t.style.height="200px",t.style.zIndex="10000",t.style.padding="10px",t.style.fontSize="14px",t.style.border="2px solid black",t.style.background="white",t.style.color="black";let n=document.createElement("button");n.innerText="Zapisz",n.style.position="fixed",n.style.top="220px",n.style.right="10px",n.style.zIndex="10000",n.onclick=function(){let o=document.getElementById("gptAnswerBox").value.trim();e=function(e){let t={};return e.split("\n").forEach((e=>{let n=e.split(":");if(2===n.length){let e=n[0].trim(),o=n[1].trim().split(",").map((e=>e.trim()));t[e]=o}})),t}(o),document.body.removeChild(t),document.body.removeChild(n)},document.body.appendChild(t),document.body.appendChild(n)}(),o=!0}function r(n){!o||"Enter"!==n.key&&1!==n.button?"\\"===n.key&&(o=!1):async function(){const n=document.querySelector('.actionContainer[style=""]');if(!n)return;const o=n.querySelector(".tinymceeffect, .nohtml");if(!o)return;const i=o.textContent.trim().toLowerCase();let r=t.find((e=>e.text===i));if(!r)return;let l=r.num,a=e[l];if(!a)return;let d=r.answers;a.forEach((e=>{d[e]&&d[e].c.click()}))}()}document.addEventListener("keydown",(function(e){"]"===e.key&&i()})),document.addEventListener("keydown",r),document.addEventListener("mousedown",r)}();
